### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Trilarion** [Leejjon/Battleround#1]
Hi,

Does the project has an open source license allowing sharing and mofication like GPL, MIT, BSD, ... or is it more like "all rights reserved"?

I could not find specific information about the license status in the code but the project looks promising.

Thanks and kind regards.

**Comment by Leejjon** [comment]
Apache License. You can do whatever you want with it. It's using old libgdx and google app engine versions and would be a lot of work to even get it running at all.

**Comment by Trilarion** [comment]
Thanks. So I could fork it and add Apache License information or do you want to add the license information? I would be fine with that too.

**Comment by Leejjon** [comment]
Added license file :) You can simply fork now.

**Comment by Trilarion** [comment]
Thanks
